name: Testing

on:
  push:
    paths:
      - '**.rs'

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install rust stable toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rust-docs
      - name: '`cargo test`'
        run: cargo test --tests
